---
title: "データ分析と線形代数03"
pagetitle: "LinearAlgebra03"
# subtitle: "サブタイトル"
# date: "`r Sys.time()`"
# abstract: ""
output:
  html_document:
    toc: TRUE
    toc_depth: 5
    toc_float: FALSE
    number_sections: TRUE
    code_folding: "show"
    highlight: "zenburn"
    theme: "flatly"
    css: ../style.css
    md_extensions: -ascii_identifiers
---

```{r SETUP, include = FALSE}
knitr::opts_chunk$set(echo       = TRUE,
                      message    = FALSE,
                      warning    = FALSE,
                      fig.align  = "center",
                      dev        = "ragg_png")
```

::: {.update-right}
UPDATE: `r Sys.time()`
:::

# はじめに

ここではデータ分析に必要な線形代数の基本的な事柄についてまとめていきます。主な範囲はベクトル、1次独立と基底、様々な行列、行列式、固有値、固有ベクトル、行列とベクトルの微分、重回帰分析、主成分分析あたりをまとめる予定です。下記の書籍を参考にして、Rで再現しながら線形代数をおさらいしていきます。

- [データ分析のための線形代数](https://www.kyoritsu-pub.co.jp/bookdetail/9784320018594)
- [Basics of Matrix Algebra for Statistics with R](https://www.routledge.com/Basics-of-Matrix-Algebra-for-Statistics-with-R/Fieller/p/book/9780367783457)
- [The Matrix Cookbook](https://www.cs.toronto.edu/~bonner/courses/2018s/csc338/matrix_cookbook.pdf)

必要なライブラリを読み込んでおきます。

```{r}
# https://github.com/friendly/matlib
library(matlib)
```

# ベクトルとは

# ベクトルの演算

# ベクトルの内積

# ベクトルと相関

# セッション情報

```{r}
sessionInfo()
```
